config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources "cotations", only: [:create]
    get '/cotations', to: 'cotations#new', as: :cotation_new

    get 'users/annonces'
    post 'users/annonces', to: 'users#annonces'

    get 'admin', to: 'users#admin'
    devise_for :users

    root to: 'pages#home'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get 'services', to: 'pages#services', as: :services

    get "specialites", to: "pages#specialites", as: :specialites
    get "contact", to: "pages#contact", as: :contact
    get "infos", to: "pages#infos", as: :infos
    get "nous_rejoindre", to: "pages#nous_rejoindre", as: :nous_rejoindre
    get "mentions_legales", to: "pages#mentions_legales", as: :mentions_legales
    get "clients", to: "pages#clients", as: :clients
    get "liens", to: "pages#liens", as: :liens

    resources "cotations", only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cotation.rb
class Cotation < MailForm::Base

	CHOICES = ["Musée / Institution",  "Galerie", "Commissaire Priseur", "Artiste", "Particulier", "Autre"]
	DEMANDES = ["Exposition", "Manutention", "Stockage", "Transport", "Déménagement", "Autre"]
	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :company
	attribute :tel
	attribute :choices
	attribute :oeuvres
	attribute :type
	attribute :address_enl
	attribute :address_liv
	attribute :description_oeuvres
	attribute :description_prestation
	attribute :date_depart
	attribute :date_fin
	attribute :nickname,  :captcha  => true

	# Declare the e-mail headers. It accepts anything the mail method
	# in ActionMailer accepts.
	def headers
	{
	  :subject => "Demande de cotation via le site Shipantiques.fr",
	  :to => ENV["GMAIL_USERNAME"],
	  :from => %("#{name}" <#{email}>)
	}
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # *** REMETTRE :registerable dans le cas d'un nouveau sign_in ***
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

	before_action :set_locale
	
	private
	
	def set_locale
	  I18n.locale = extract_locale || I18n.default_locale
	end

	def extract_locale
	  parsed_locale = params[:locale]
	  I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
	end

	def default_url_options
	  { locale: I18n.locale }
	end

end

app/controllers/cotations_controller.rb
class CotationsController < ApplicationController
	skip_before_action :authenticate_user!
	
	def new
		@cotation = Cotation.new
	end

	def create
		@cotation = Cotation.new(params[:cotation])
		@cotation.request = request

		@cotation.choices = params[:cotation][:choices]
		if  @cotation.choices == [""]
			@cotation.choices = nil
		end 

		@cotation.type = params[:cotation][:type]
		if  @cotation.type == [""]
			@cotation.type = nil
		end 

		if @cotation.oeuvres != nil
			@cotation.oeuvres = params[:cotation][:oeuvres]
			@cotation.oeuvres.each do |actiondispatch|
				Cloudinary::Uploader.upload(actiondispatch.tempfile,folder:"/Cotations")
			end
			@cotation.oeuvres = 'Le client à télécharger des images, se rendre sur www.cloudinary.com / Media Library / Cotations Folder pour accéder aux images'
		end

		if @cotation.deliver
		  flash.now[:notice] = 'Votre demande de cotation à bien été transmise, nous allons revenir vers vous au plus vite'
		else
		  flash.now[:error] = 'Merci de vérifier votre saisie svp'
		  render :new
		end
	end

	private

	def contact_params
		params.require(:cotation).permit(:email, :name, :company, :tel, :message, :choices, :oeuvres, :type, :address_enl, :address_liv, :description_oeuvres, :description_prestation, :date_depart, :date_fin)
	end  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :services, :specialites, :contact, :infos, :nous_rejoindre, :mentions_legales, :clients, :liens]

  def home
  end

  def services
  end 

  def specialites
  end

  def contact
  end  

  def infos
  end  

  def nous_rejoindre
  end  

  def mentions_legales
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def destroy
  	redirect_to root_path
  end
  
  def admin
  	redirect_to user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cotations/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/cotations/new.html.erb
<div class="site-blocks-cover inner-page-cover overlay", id="section-clients" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">

      <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
        <h1 class="text-white font-weight-light text-uppercase font-weight-bold">Cotations</h1>
        <p class="breadcrumb-custom"><%= link_to "Accueil", root_path %> <span class="mx-2">&gt;</span> <span>Demande de cotations</span></p>
      </div>
    </div>
  </div>
</div>


<div class="cotation-container" align="center">

  <%= simple_form_for @cotation, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true, label: "Votre Nom"  %>
    <%= f.input :email, :required => true %>
    <%= f.input :company, label: "Nom de votre société" %>
    <%= f.input :tel, label: "Téléphone" %>
    <%= f.input :choices, as: :check_boxes, collection: Cotation::CHOICES, label: "Vous êtes :" %>
    <%= f.input :oeuvres, as: :file, input_html: { multiple: true }, label: "Description des oeuvres"%>
    <%= f.input :type, as: :check_boxes, collection: Cotation::DEMANDES, label: "Type de demande :" %>
    <%= f.input :address_enl, label: "Adresse (addresse de l'opération ou adresse d'enlèvement des oeuvres si applicable)" %>
    <%= f.input :address_liv, label: "Adresse 2 (addresse de l'opération ou adresse d'enlèvement des oeuvres si applicable)" %>
    <%= f.input :description_oeuvres, :as => :text, label: "Brève description des oeuvres (quantité, dimensions, matière, artiste, valeur d'assurance" %>
    <%= f.input :description_prestation, :as => :text, label: "Brève description de la prestation demandée" %>
    <%= f.label :date, label: "Dates demandées pour la prestation"   %>
    <%= f.input :date_depart, as: :date, label: "Date de départ de la prestation" %>
    <%= f.input :date_fin, as: :date, label: "Date de fin de la prestation" %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Envoyer', :class=> "btn btn-cloudinary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ship Antiques, French packer and shipper of Fine Arts and Antiques</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <!-- Google result text-->
    <title>Ship Antiques, French packer and shipper of Fine Arts and Antiques</title>
    <!-- Google result description-->
    <meta name="description" content="Ship Antiques, French packer and shipper of Fine Arts and Antiques" />

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-149626680-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-149626680-2');
    </script>

    <!-- Facebook results -->
    <meta property="og:title" content="Ship Antiques, French packer and shipper of Fine Arts and Antiques">
    <meta property="og:image" content="facebook-card.jpg">
    <meta property="og:description" content="Ship Antiques is your best partner for pick up, packing & crating, multimodal shipping and customs clearance all over the world.">
    <meta property="og:site_name" content="Ship Antiques"/>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= favicon_link_tag asset_path('https://res.cloudinary.com/shipantiques/image/upload/v1580912405/images-site/logo_favicon_vmrr4o.png') %>

    <!--     AOS ANIMATION ON SCROLL -->    
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@next/dist/aos.js"> </script>
    
    <script src="https://kit.fontawesome.com/7cb59a042f.js" crossorigin="anonymous"></script>

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/cookies' %>
    <%= render 'shared/footer' %>
    
    <%= javascript_pack_tag 'application' %>

  </body>

</html>

app/views/pages/clients.html.erb
<div class="site-blocks-cover inner-page-cover overlay", id="section-clients" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">

      <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
        <h1 class="text-white font-weight-light text-uppercase font-weight-bold"><%= t '.titre'  %></h1>
        <p class="breadcrumb-custom"><%= link_to t(".accueil"), root_path %> <span class="mx-2">&gt;</span> <span><%= t '.titre'  %></span></p>
      </div>
    </div>
  </div>
</div>


<div class="site-section bg-light pb-0" id="section-specialites">
  <div class="container pb-5">

    <div id="clients-antiquaires">
      <div class="container-specialites-2">
        <div class="row justify-content-center mb-5" data-aos="fade-up">
          <div class="col-md-9 text-center border-primary">
            <h2 class="text-color-ship"><%= t ".gal_titre" %></h2>
            <p class="color-black-opacity-5"></p>
          </div>
        </div>

        <div class="row align-items-stretch justify-content-center">
          <div class="col-12 mb-10 mb-lg-10" data-aos="fade-up" data-aos-delay="200">
            <div class="services-description-2">
              <div class="services-description-image">  
                <%= image_tag('blog_1.jpg')%>
              </div>
              <div class="services-description-texte services-description-texte__clients">
                <%= t '.gal_texte' %>         
              </div>
            </div>
          </div>
        </div>    
      </div>

    </div>

    <div id="clients-decorateurs">

      <div class="container-specialites-2">

        <div class="row justify-content-center mb-5" data-aos="fade-up">
          <div class="col-md-9 text-center border-primary">
            <h2 class="text-color-ship"><%= t ".archi_titre" %></h2>
            <p class="color-black-opacity-5"></p>
          </div>
        </div>

        <div class="row align-items-stretch justify-content-center">
          <div class="col-12 mb-10 mb-lg-10" data-aos="fade-up" data-aos-delay="200">
              <div class="services-description-2" id="services-description-2-reverse">
                <div class="services-description-texte services-description-texte__clients">            
                  <%= t '.archi_texte'  %>
                </div>
                <div class="services-description-image">  
                  <%= image_tag('blog_2.jpg')%>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>

    <div id="clients-luxe">
      <div class="container-specialites-2">

        <div class="row justify-content-center mb-5" data-aos="fade-up">
          <div class="col-md-9 text-center border-primary">
            <h2 class="text-color-ship"><%= t '.marques_titre'  %></h2>
            <p class="color-black-opacity-5"></p>
          </div>
        </div>

        <div class="row align-items-stretch justify-content-center">

          <div class="col-12 mb-10 mb-lg-10" data-aos="fade-up" data-aos-delay="200">
            <div class="services-description-2">
              <div class="services-description-image">  
                <%= image_tag('blog_1.jpg')%>
              </div>
              <div class="services-description-texte services-description-texte__clients">
                <%= t '.marques_texte'  %>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>

    <div id="clients-particuliers">

      <div class="container-specialites-2">

        <div class="row justify-content-center mb-5" data-aos="fade-up">
          <div class="col-md-9 text-center border-primary">
            <h2 class="text-color-ship"><%= t ".particuliers_titre" %></h2>
            <p class="color-black-opacity-5"></p>
          </div>
        </div>

        <div class="row align-items-stretch justify-content-center">
          <div class="col-12 mb-10 mb-lg-10" data-aos="fade-up" data-aos-delay="200">
              <div class="services-description-2" id="services-description-2-reverse">
                <div class="services-description-texte services-description-texte__clients">            
                  <%= t '.particuliers_texte'  %>
                </div>
                <div class="services-description-image">  
                  <%= image_tag('blog_2.jpg')%>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>

</div>

app/views/pages/contact.html.erb
<div class="site-blocks-cover inner-page-cover overlay", id="section-clients" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">

      <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
        <h1 class="text-white font-weight-light text-uppercase font-weight-bold"><%= t '.titre' %></h1>
        <p class="breadcrumb-custom"><%= link_to t(".accueil"), root_path %> <span class="mx-2">&gt;</span> <span><%= t '.titre' %></span></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/cotations.html.erb
<div class="site-blocks-cover inner-page-cover overlay", id="section-clients" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">

      <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
        <h1 class="text-white font-weight-light text-uppercase font-weight-bold">Cotations</h1>
        <p class="breadcrumb-custom"><%= link_to "Accueil", root_path %> <span class="mx-2">&gt;</span> <span>Demande de cotations</span></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_cookies.html.erb
<div id="cookieConsent" style='display: none'>
    <div id="closeCookieConsent">x</div>
    <%= t "shared._cookies.content" %>
    <%= link_to(t('shared._cookies.link'), mentions_legales_path) %>
    <a class="cookieConsentOK"><%= t "shared._cookies.close" %></a>
</div>

app/views/shared/_footer.html.erb
<footer class="site-footer">
  <div class="container">
    <div class="footer-info">

      <div class="footer-1">
        <h2 class="footer-heading mb-4"><%= t 'shared._footer.a_propos' %></h2>
        <p style="text-align: justify;"><%= t 'shared._footer.a_propos_texte' %></p>
      </div>

      <div class="footer-2">
        <h2 class="footer-heading mb-4"><%= t 'shared._footer.links' %></h2>
        <ul class="list-unstyled">
          <li><%= link_to t('shared._footer.a_propos'), root_path(:anchor => "section-about") %></li>
          <li><%= link_to t('shared._footer.services'), services_path %> </li>
          <li><%= link_to t('shared._footer.nos_clients'), clients_path %></li>
          <li><%= link_to t('shared._footer.infos_pratiques'), infos_path %> </li>
        </ul>
      </div>

      <div class="footer-3">
        <h2 class="footer-heading mb-4"> <%= t 'shared._footer.trouvez_nous' %></h2>
        <%= link_to cl_image_tag("https://res.cloudinary.com/shipantiques/image/upload/v1580912404/images-site/facebook-logo_k5olqk.png"), "https://www.facebook.com/SHIP-ANTIQUES-168465044114/", alt: 'facebook-logo', target: '_blank' %>
        <br>
        <%= link_to cl_image_tag("https://res.cloudinary.com/shipantiques/image/upload/v1580912405/images-site/linkedin-logo_dcnvqx.png"), "https://fr.linkedin.com/company/ship-antiques", alt: 'linkedin-logo', target: '_blank' %>
      </div>

    </div>
  </div>

  <div class="pt-3 pb-3 text-center">
    <p>
      <small class="block">&copy;
        <script>document.write(
          new Date().getFullYear());
        </script>
         Ship Antiques. All Rights Reserved.
         <br>
         Designed &amp; Developed by
         <a href="https://www.delage.dev/" target="_blank">
         delage.dev</a>
      </small>
    </p>
  </div>
</footer>

app/views/shared/_infos.html.erb
<div class="site-section" id="section-infos">

  <div class="container">
      <div class="row justify-content-center" data-aos="fade-up">
        <div class="col-md-7 text-center border-primary">
          <h2 class="mb-0 text-color-ship"><%= t 'shared._infos.titre' %></h2>
          <p class="color-black-opacity-5"></p>
        </div>
        <div id='btn-infos'>
            <a href="mailto:&#099;&#111;&#110;&#116;&#097;&#099;&#116;&#064;&#115;&#104;&#105;&#112;&#097;&#110;&#116;&#105;&#113;&#117;&#101;&#115;&#046;&#102;&#114;" class="btn btn-prk"><%= t 'shared._infos.contactez_nous' %></a>
            <%= link_to(t('shared._infos.demande_devis'), cotation_new_path, class: 'btn btn-prk-2') %>
        </div>
      </div>

      <div class="container-infos">
        <div class="nous-trouver">
          <div id="infos-map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2622.730818795451!2d2.339151315675923!3d48.9014669792918!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66ef14c5930dd%3A0x538957a6f85756cf!2sSHIP%20ANTIQUES!5e0!3m2!1sen!2sfr!4v1572855116482!5m2!1sen!2sfr" allowfullscreen=""></iframe>
          </div>
          <div class="address">
            <p class="mb-4 font-weight-bold"><%= t 'shared._infos.address_1' %></p>
            <p class="mb-0 font-weight-bold"><%= t 'shared._infos.address_2' %></p>
            <p class="mb-0"><%= t 'shared._infos.address_3' %></p>
            <p class="mb-4"><%= t 'shared._infos.address_4' %></p>

            <p class="mb-0 font-weight-bold"><%= t 'shared._infos.phone_1' %></p>
            <p class="mb-4"><%= t 'shared._infos.phone_2' %></p>

            <p><a href="mailto:&#099;&#111;&#110;&#116;&#097;&#099;&#116;&#064;&#115;&#104;&#105;&#112;&#097;&#110;&#116;&#105;&#113;&#117;&#101;&#115;&#046;&#102;&#114;" class="btn btn-prk"><%= t 'shared._infos.contactez_nous' %></a></p>
          </div>
        </div>
      </div>

      <div class="p-4 bg-white">
        <p style="text-align: center;"><%= t 'shared._infos.accueil_equipe_html' %></p>
      </div>

      <div class="container-infos">
        <div class="nous-trouver">
          <div id="infos-map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2618.9408698061097!2d2.499436215678444!3d48.97364997929893!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6151d5475f56d%3A0xc8d30f4ded510386!2s154%20All%C3%A9e%20des%20%C3%89rables%2C%2093420%20Villepinte!5e0!3m2!1sen!2sfr!4v1579935903211!5m2!1sen!2sfr"allowfullscreen=""></iframe>
          </div>
          <div class="address">
            <p class="mb-4 font-weight-bold"><%= t 'shared._infos.address_depot_1_html' %></p>
            <p class="mb-0 font-weight-bold"><%= t 'shared._infos.address_depot_2_html' %></p>
            <p class="mb-0"><%= t 'shared._infos.address_depot_3_html' %></p>
            <p class="mb-0"><%= t 'shared._infos.address_depot_4_html' %></p>
            <p class="mb-0"><%= t 'shared._infos.address_depot_5_html' %></p>
            <p class="mb-0 font-weight-bold"><%= t 'shared._infos.phone_1' %></p>
            <p class="mb-4"><%= t 'shared._infos.phone_2' %></p>

          </div>
        </div>
      </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- *** navbar_prk *** -->

<div class="site-mobile-menu site-navbar-target">
  <div class="site-mobile-menu-header">
    <div class="site-mobile-menu-close mt-3">
      <span class="icon-close2 js-menu-toggle"></span>
    </div>
  </div>
  <div class="site-mobile-menu-body"></div>
</div>

<header class="site-navbar js-site-navbar site-navbar-target" role="banner" id="site-navbar">
  <div class="container">
    <div class="desktop-nav">
      <div class="site-logo">
        <%= link_to cl_image_tag('https://res.cloudinary.com/shipantiques/image/upload/v1580912405/images-site/logo_blank_leiiqq.png', alt: "logo"), root_path %>
      </div>
      <div class="col-12 col-md-10 d-none d-xl-block">
        <nav class="site-navigation position-relative text-center" role="navigation">
          <ul class="site-menu js-clone-nav mx-auto d-none d-lg-block">

            <li class="has-children">
              <% if current_page?(root_path) || current_page?(specialites_path) || current_page?(clients_path) %>
                <div class="navbar-middle-button active">
              <% else %>
                <div class="navbar-middle-button">
              <% end %>
                  <%= link_to t('shared._navbar.a_propos_menu.a_propos'), root_path(:anchor => "section-about")  %>
                </div>
              <ul class="dropdown">
                <li><%= link_to t('shared._navbar.a_propos_menu.ship_antiques'), root_path(:anchor => "section-about"), class: "nav-link"  %></li>
                <li><%= link_to t('shared._navbar.a_propos_menu.nos_specialites'), specialites_path %></li>
                <li><%= link_to t('shared._navbar.a_propos_menu.nos_clients'), clients_path, class: "nav-link"  %></li>
              </ul>
            </li>

            <li class="has-children">
              <% if current_page?(services_path) %>
                <div class="navbar-middle-button active">
              <% else %>
                <div class="navbar-middle-button">
              <% end %>
                <%= link_to t('shared._navbar.services_menu.services'), services_path %>
              </div> 
              <ul class="dropdown">
               <li> <%= link_to t('shared._navbar.services_menu.enl_liv_manut'), services_path(:anchor => "services-enlevement"), class: "nav-link"  %> </li>
               <li> <%= link_to t('shared._navbar.services_menu.protection_emballage'), services_path(:anchor => "services-protection"), class: "nav-link"  %> </li>                 
               <li> <%= link_to t('shared._navbar.services_menu.stock_et_gestion'), services_path(:anchor => "services-stockage"), class: "nav-link"  %> </li>
               <li> <%= link_to t('shared._navbar.services_menu.gestion_admin'), services_path(:anchor => "services-gestion"), class: "nav-link"  %> </li>
               <li> <%= link_to t('shared._navbar.services_menu.tpt_multi'), services_path(:anchor => "services-multimodal"), class: "nav-link"  %> </li>
              </ul>
            </li>

            <li class="has-children">
              <% if current_page?(infos_path) || current_page?(cotation_new_path) %>
                <div class="navbar-middle-button active">
              <% else %>
                <div class="navbar-middle-button">
              <% end %>
                <%= link_to t('shared._navbar.contacts_et_cotations_menu.contacts_et_cotations'), cotation_new_path %>
              </div>
              <ul class="dropdown">
                <li><%= link_to t('shared._navbar.contacts_et_cotations_menu.demande_cot'), cotation_new_path %></li>
                <li><%= link_to t('shared._navbar.contacts_et_cotations_menu.nous_trouver'), infos_path %></li>
              </ul>
            </li>

            <li class="has-children">
              <% if current_page?(mentions_legales_path) || current_page?(nous_rejoindre_path) || current_page?(liens_path) %>
                <div class="navbar-middle-button active">
              <% else %>
                <div class="navbar-middle-button">
              <% end %>
                <%= link_to t('shared._navbar.infos_pratiques_menu.infos_pratiques'), mentions_legales_path %>
              </div>
              <ul class="dropdown">
                <li><%= link_to t('shared._navbar.infos_pratiques_menu.mentions_legales'), mentions_legales_path %></li>
                <li><%= link_to t('shared._navbar.infos_pratiques_menu.nous_rejoindre'), nous_rejoindre_path %></li>
                <li><%= link_to t('shared._navbar.infos_pratiques_menu.liens_utiles'), liens_path %></li>
              </ul>
            </li>

            <% if user_signed_in? %>
            <li class="has-children">
              <%= link_to "Admin", users_annonces_path %>
              <ul class="dropdown">
                  <li><%= link_to "Gerer les annonces", users_annonces_path %></li>
                  <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete%></li>
              </ul>
            <% end %>

            <li class="has-children" id="flagOnNavbar">
              <% if I18n.locale.to_s == 'en' %>
                <a class="nav-link first-flag"><%= cl_image_tag 'https://res.cloudinary.com/shipantiques/image/upload/v1580912405/images-site/fr-flag_dicsiq.png', alt: 'logo', width: 20, height: 20 %></a>
              <% else %>
                <a class="nav-link first-flag"><%= cl_image_tag 'https://res.cloudinary.com/shipantiques/image/upload/v1580912405/images-site/us-flag_tv0tsg.png', alt: 'logo', width: 20, height: 20 %></a>
              <% end %>
              <ul id="flags" class="dropdown">

                <li>
                  <%= link_to root_path(locale: :fr), class: 'nav-link' do %>
                    <%= cl_image_tag 'https://res.cloudinary.com/shipantiques/image/upload/v1580912405/images-site/fr-flag_dicsiq.png', alt: 'logo', width: 20, height: 20 %>
                  <% end %>
                  <%= link_to root_path(locale: :en), class: 'nav-link'  do %>
                    <%= cl_image_tag 'https://res.cloudinary.com/shipantiques/image/upload/v1580912405/images-site/us-flag_tv0tsg.png', alt: 'logo', width: 20, height: 20 %>
                  <% end %>
                </li>

              </ul>
            </li>
          </ul>
        </nav>
      </div>
      <div class="d-inline-block d-xl-none ml-md-0 mr-auto py-3" id="hamburger">
        <span class="site-menu-toggle js-menu-toggle">
          <%= cl_image_tag "https://res.cloudinary.com/shipantiques/image/upload/v1580912405/images-site/hamburger_x2w7o0.png", alt: "Menu", width: 70 %>
        </span>
      </div>
    </div>
  </div>
</header>